<a href="https://colab.research.google.com/github/ni190304/DAV_44/blob/master/DAV_Exp1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Experiment 1:

Python Libraries:

*   Pandas
*   Numpy

**Pandas**:

Pandas, an open-source data manipulation and analysis library for Python, plays a pivotal role in the data science ecosystem. Built on top of NumPy, it introduces two primary data structures - DataFrame and Series, simplifying the handling of structured data. Pandas facilitates tasks like data cleaning, exploration, and transformation through its versatile indexing, merging, and reshaping capabilities. It is instrumental in handling heterogeneous and labeled data, making it an essential tool for data preprocessing and analysis. Pandas integrates seamlessly with other Python libraries and is widely utilized in fields such as finance, statistics, and machine learning, contributing to its popularity in the data science community.

In [ ]:
import pandas as pd
import numpy as np


In [ ]:
cars = pd.Series(["BMW","Audi","Chevrolet"])
cars


0          BMW
1         Audi
2    Chevrolet
dtype: object

In [ ]:
colors = pd.Series(["Blue","Grey","Red"])
colors

0    Blue
1    Grey
2     Red
dtype: object

In [ ]:
car_data = pd.DataFrame({"Car": cars, "Color": colors})
car_data

Car Color
0        BMW  Blue
1       Audi  Grey
2  Chevrolet   Red

In [ ]:
dataset = pd.read_csv('/content/drive/MyDrive/Electric_Vehicle_Population_Data.csv')

dataset.head()

VIN (1-10)     County     City State  Postal Code  Model Year    Make  \
0  3C3CFFGE4E     Yakima   Yakima    WA      98902.0        2014    FIAT   
1  5YJXCBE40H   Thurston  Olympia    WA      98513.0        2017   TESLA   
2  3MW39FS03P       King   Renton    WA      98058.0        2023     BMW   
3  7PDSGABA8P  Snohomish  Bothell    WA      98012.0        2023  RIVIAN   
4  5YJ3E1EB8L       King     Kent    WA      98031.0        2020   TESLA   

     Model                   Electric Vehicle Type  \
0      500          Battery Electric Vehicle (BEV)   
1  MODEL X          Battery Electric Vehicle (BEV)   
2     330E  Plug-in Hybrid Electric Vehicle (PHEV)   
3      R1S          Battery Electric Vehicle (BEV)   
4  MODEL 3          Battery Electric Vehicle (BEV)   

   Clean Alternative Fuel Vehicle (CAFV) Eligibility  Electric Range  \
0            Clean Alternative Fuel Vehicle Eligible              87   
1            Clean Alternative Fuel Vehicle Eligible             200   
2              Not eligible due to low battery range              20   
3  Eligibility unknown as battery range has not b...               0   
4            Clean Alternative Fuel Vehicle Eligible             322   

   Base MSRP  Legislative District  DOL Vehicle ID  \
0          0                  14.0         1593721   
1          0                   2.0       257167501   
2          0                  11.0       224071816   
3          0                  21.0       260084653   
4          0                  33.0       253771913   

                  Vehicle Location  \
0   POINT (-120.524012 46.5973939)   
1     POINT (-122.817545 46.98876)   
2  POINT (-122.1298876 47.4451257)   
3      POINT (-122.1873 47.820245)   
4  POINT (-122.2012521 47.3931814)   

                                Electric Utility  2020 Census Tract  
0                                     PACIFICORP       5.307700e+10  
1                         PUGET SOUND ENERGY INC       5.306701e+10  
2  PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA)       5.303303e+10  
3                         PUGET SOUND ENERGY INC       5.306105e+10  
4  PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA)       5.303303e+10

# Data Description

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 166800 entries, 0 to 166799
Data columns (total 17 columns):
 #   Column                                             Non-Null Count   Dtype  
---  ------                                             --------------   -----  
 0   VIN (1-10)                                         166800 non-null  object 
 1   County                                             166795 non-null  object 
 2   City                                               166795 non-null  object 
 3   State                                              166800 non-null  object 
 4   Postal Code                                        166795 non-null  float64
 5   Model Year                                         166800 non-null  int64  
 6   Make                                               166800 non-null  object 
 7   Model                                              166800 non-null  object 
 8   Electric Vehicle Type                              166800 non-null  object

In [ ]:
dataset.describe()

Postal Code     Model Year  Electric Range      Base MSRP  \
count  166795.000000  166800.000000   166800.000000  166800.000000   
mean    98173.713750    2020.341793       61.508993    1152.723171   
std      2442.584415       3.001465       93.271747    8661.081091   
min      1730.000000    1997.000000        0.000000       0.000000   
25%     98052.000000    2018.000000        0.000000       0.000000   
50%     98122.000000    2021.000000        0.000000       0.000000   
75%     98371.000000    2023.000000       84.000000       0.000000   
max     99577.000000    2024.000000      337.000000  845000.000000   

       Legislative District  DOL Vehicle ID  2020 Census Tract  
count         166440.000000    1.668000e+05       1.667950e+05  
mean              29.178941    2.172420e+08       5.297709e+10  
std               14.853534    7.727458e+07       1.569754e+09  
min                1.000000    4.385000e+03       1.001020e+09  
25%               18.000000    1.790741e+08       5.303301e+10  
50%               33.000000    2.244045e+08       5.303303e+10  
75%               42.000000    2.513421e+08       5.305307e+10  
max               49.000000    4.792548e+08       5.603300e+10

In [ ]:
dataset.columns

Index(['VIN (1-10)', 'County', 'City', 'State', 'Postal Code', 'Model Year',
       'Make', 'Model', 'Electric Vehicle Type',
       'Clean Alternative Fuel Vehicle (CAFV) Eligibility', 'Electric Range',
       'Base MSRP', 'Legislative District', 'DOL Vehicle ID',
       'Vehicle Location', 'Electric Utility', '2020 Census Tract'],
      dtype='object')

In [ ]:
dataset.dtypes

VIN (1-10)                                            object
County                                                object
City                                                  object
State                                                 object
Postal Code                                          float64
Model Year                                             int64
Make                                                  object
Model                                                 object
Electric Vehicle Type                                 object
Clean Alternative Fuel Vehicle (CAFV) Eligibility     object
Electric Range                                         int64
Base MSRP                                              int64
Legislative District                                 float64
DOL Vehicle ID                                         int64
Vehicle Location                                      object
Electric Utility                                      object
2020 Census Tract       

**Numpy**

NumPy, short for Numerical Python, is a powerful open-source library for numerical computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with an extensive collection of high-level mathematical functions to operate on these arrays. NumPy is a fundamental package for scientific computing and data analysis, serving as the foundation for many other libraries in the Python ecosystem. Its efficient array operations, broadcasting capabilities, and integration with other data science tools make it essential for tasks like linear algebra, statistical analysis, and machine learning. NumPy's simplicity and performance contribute to its widespread adoption in academia, industry, and research.

In [ ]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [ ]:
type(a1)

numpy.ndarray

In [ ]:
a2 = np.array([[[1, 2, 3],
                [4, 5, 6],
               [7, 8, 9]],
                [[10, 11, 12],
               [13, 14, 15],
                [16, 17, 18]]])
a2.shape

(2, 3, 3)

In [ ]:
a2.ndim, a2.dtype , a2.size

(3, dtype('int64'), 18)

# Creating a One's and Zeroes Array

In [ ]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
zeroes = np.zeros((3,4))
zeroes

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
ones.dtype, zeroes.dtype

(dtype('float64'), dtype('float64'))

# Creating a Range & Random Array

In [ ]:
range_array = np.arange(2,10,2)
range_array

array([2, 4, 6, 8])

In [ ]:
random_array = np.random.randint(0, 10 , size=(3,5))
random_array

array([[4, 4, 5, 9, 3],
       [1, 1, 9, 1, 7],
       [2, 2, 2, 4, 0]])

R libraries:

*   dplyr
*   tidyr





The package "dplyr" comprises many functions that perform mostly used data manipulation operations such as applying filter, selecting specific columns, sorting data, adding or deleting columns and aggregating data. Another most important advantage of this package is that it's very easy to learn and use dplyr functions. Also easy to recall these functions.

**dplyr**

The package "dplyr" comprises many functions that perform mostly used data manipulation operations such as applying filter, selecting specific columns, sorting data, adding or deleting columns and aggregating data. Another most important advantage of this package is that it's very easy to learn and use dplyr functions. Also easy to recall these functions.

In [ ]:
install.packages("dplyr")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)



In [ ]:
library(dplyr)


Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union




In [ ]:
data = read.csv('/content/drive/MyDrive/Electric_Vehicle_Population_Data.csv')

head(data, 5)

VIN..1.10. County    City    State Postal.Code Model.Year Make   Model  
1 3C3CFFGE4E Yakima    Yakima  WA    98902       2014       FIAT   500    
2 5YJXCBE40H Thurston  Olympia WA    98513       2017       TESLA  MODEL X
3 3MW39FS03P King      Renton  WA    98058       2023       BMW    330E   
4 7PDSGABA8P Snohomish Bothell WA    98012       2023       RIVIAN R1S    
5 5YJ3E1EB8L King      Kent    WA    98031       2020       TESLA  MODEL 3
  Electric.Vehicle.Type                 
1 Battery Electric Vehicle (BEV)        
2 Battery Electric Vehicle (BEV)        
3 Plug-in Hybrid Electric Vehicle (PHEV)
4 Battery Electric Vehicle (BEV)        
5 Battery Electric Vehicle (BEV)        
  Clean.Alternative.Fuel.Vehicle..CAFV..Eligibility            Electric.Range
1 Clean Alternative Fuel Vehicle Eligible                       87           
2 Clean Alternative Fuel Vehicle Eligible                      200           
3 Not eligible due to low battery range                         20           
4 Eligibility unknown as battery range has not been researched   0           
5 Clean Alternative Fuel Vehicle Eligible                      322           
  Base.MSRP Legislative.District DOL.Vehicle.ID Vehicle.Location               
1 0         14                     1593721      POINT (-120.524012 46.5973939) 
2 0          2                   257167501      POINT (-122.817545 46.98876)   
3 0         11                   224071816      POINT (-122.1298876 47.4451257)
4 0         21                   260084653      POINT (-122.1873 47.820245)    
5 0         33                   253771913      POINT (-122.2012521 47.3931814)
  Electric.Utility                              X2020.Census.Tract
1 PACIFICORP                                    53077000700       
2 PUGET SOUND ENERGY INC                        53067012331       
3 PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA) 53033025803       
4 PUGET SOUND ENERGY INC                        53061051927       
5 PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA) 53033029305

In [ ]:
sample_n(data,3)

VIN..1.10. County City          State Postal.Code Model.Year Make    Model  
1 KMHM54ACXR King   Mercer Island WA    98040       2024       HYUNDAI IONIQ 6
2 KM8KMDAFXP Pierce Tacoma        WA    98422       2023       HYUNDAI IONIQ 5
3 5YJ3E1EB7N King   Seattle       WA    98109       2022       TESLA   MODEL 3
  Electric.Vehicle.Type         
1 Battery Electric Vehicle (BEV)
2 Battery Electric Vehicle (BEV)
3 Battery Electric Vehicle (BEV)
  Clean.Alternative.Fuel.Vehicle..CAFV..Eligibility            Electric.Range
1 Eligibility unknown as battery range has not been researched 0             
2 Eligibility unknown as battery range has not been researched 0             
3 Eligibility unknown as battery range has not been researched 0             
  Base.MSRP Legislative.District DOL.Vehicle.ID Vehicle.Location              
1 0         41                   260832099      POINT (-122.2377542 47.582905)
2 0         27                   218781412      POINT (-122.38578 47.28971)   
3 0         43                   195273704      POINT (-122.34848 47.632405)  
  Electric.Utility                                                               
1 PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA)                                  
2 BONNEVILLE POWER ADMINISTRATION||CITY OF TACOMA - (WA)||PENINSULA LIGHT COMPANY
3 CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA)                                   
  X2020.Census.Tract
1 53033024602       
2 53053940005       
3 53033007301

**tidyr**

The goal of tidyr is to help you create tidy data.

Tidy data is data where:

Every column is a variable.

Every row is an observation.

Every cell is a single value.


In [ ]:
install.packages("tidyverse")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)



In [ ]:
library(tidyr)

In [ ]:
data <- data.frame(
  ID = c(1, 2, 3),
  Jan = c(10, 15, 20),
  Feb = c(12, 18, 22),
  Mar = c(14, 20, 25)
)


print("Original data:")
print(data)

[1] "Original data:"
  ID Jan Feb Mar
1  1  10  12  14
2  2  15  18  20
3  3  20  22  25


In [ ]:
# Reshape data using gather(vertical)
gathered_data <- gather(data, key = "Month", value = "Value", -ID)
print("\nReshaped data using gather:")
print(gathered_data)

[1] "\nReshaped data using gather:"
  ID Month Value
1  1   Jan    10
2  2   Jan    15
3  3   Jan    20
4  1   Feb    12
5  2   Feb    18
6  3   Feb    22
7  1   Mar    14
8  2   Mar    20
9  3   Mar    25


In [ ]:
# Reshape data using spread(horizontal)
spread_data <- spread(gathered_data, key = "Month", value = "Value")
print("\nReshaped data using spread:")
print(spread_data)

[1] "\nReshaped data using spread:"
  ID Feb Jan Mar
1  1  12  10  14
2  2  18  15  20
3  3  22  20  25
